export const TYPES = {
  WINDOW: Symbol.for('WINDOW'),
  BASE_URL_API: Symbol.for('BASE_URL_API'),
  EXECUTOR_LINK: Symbol.for('EXECUTOR_LINK'),
  LOGGER_LINK: Symbol.for('LOGGER_LINK'),
  LOGGER: Symbol.for('LOGGER'),
  RUNNER: Symbol.for('RUNNER'),
  ESSENTIAL_LINK_REPOSITORY: Symbol.for('ESSENTIAL_LINK_REPOSITORY'),
  ESSENTIAL_LINK_GET_ALL_QUERY: Symbol.for('ESSENTIAL_LINK_GET_ALL_QUERY'),
};
